---
- hosts: abc
  gather_facts: no
  tasks:
    - name: copy war file 
      copy: 
        src: "/root/.jenkins/workspace/val_pipeline/target/gameoflife-0.0.1.war"
        dest: "/root/apache-tomcat-9.0.10/webapps/gameoflife-0.0.1.war"
        mode: 0777
        
    - name: start tomcat
      shell: "cd /root/apache-tomcat-9.0.10/bin; ./startup.sh"
      become: true
      
    - name: execute war
      shell: "cd /root/apache-tomcat-9.0.10/webapps; nohup java -jar gameoflife-0.0.1.war &"
      become: true
